Improve handling of Paging Arguments
MassiveCraft/MassiveCore pull request #337
Opened 2018-02-10 10:05 UTC by zeotom

Prior to fix the Pager buttons would ignore any supplied arguments unless one of those arguments was the Page.

e.g.
`/faction relation list Enigma` would be given a next button of `/faction relation list 2` rather than `/faction relation list 2 Enigma`

Fix provides fallback, allowing implicit page number to ensure the handling of provided arguments.

2018-02-10 17:35 UTC, TheComputerGeek2 requested changes

2018-02-10 17:35 UTC, TheComputerGeek2 commented on src/com/massivecraft/massivecore/util/Txt.java
> +				arguments.add(0,number);
We use either single line conditionals or brackets. You can find examples of this a little lower in this file.

2018-02-10 17:35 UTC, TheComputerGeek2 commented on src/com/massivecraft/massivecore/util/Txt.java
> +				arguments.add(0,number);
It might be beneficial to write a brief comment about what this section is doing as well.

2018-02-10 22:35 UTC, zeotom commented
Changes implemented as requested.

2018-02-11 10:25 UTC, oloflarsson commented on src/com/massivecraft/massivecore/util/Txt.java
> +			if (args.contains(oldNumber)) {
This breaks with the MassiveCraft code style. We use Allman bracket placement meaning that `{` and `}` should be on dedicated lines.

2018-02-11 10:25 UTC, oloflarsson commented on src/com/massivecraft/massivecore/util/Txt.java
> +			else {
The same goes for this bracket.

2018-02-11 11:12 UTC, zeotom commented
Brace placement sorted. Had forgotten to import the Massive Codestyle to my new dev environment.

2018-03-04 21:15 UTC, TheComputerGeek2 approved these changes

2018-04-01 09:52 UTC, oloflarsson requested changes

2018-04-01 09:52 UTC, oloflarsson commented on src/com/massivecraft/massivecore/util/Txt.java
> +				// add the new page number as the first argument
I feel like we are making an assumption here. We can not really be sure that the first argument is the page. This is a guess really.

So I would propose looking at the `MassiveCommand` and the parameters it has. When adding a page parameter we are pretty sure the name is going to be "page" because we use `Parameter.getPage()` to generate the Parameter instance in almost all cases.

How about we loop over the parameters of the MassiveCommand and actually figure out what the index is.

It should be noted that the current `arguments.indexOf(oldNumber)` is also flawed. What if there is another integer parameter than the page. We may end up incrementing the wrong one of they are the same value.

2018-04-02 00:58 UTC, CS-Birb commented
Revised in response to review and requested changes.

Now aims to identify the page argument where possible, otherwise falls back to the first index found matching the old page number (as was old behaviour); failing that add the new page number as a leading argument.

2018-04-02 14:42 UTC, oloflarsson requested changes

2018-04-02 14:42 UTC, oloflarsson commented on src/com/massivecraft/massivecore/util/Txt.java
> +			}
This approach assumes that there will always be one. What if that isn't the case?

I would propose adding a new method to MassiveCommand `massiveCommand.getPageParameterIndex()` that would return -1 if no page parameter could be found. That might adhere better to object oriented style?

2018-04-02 14:42 UTC, oloflarsson commented on src/com/massivecraft/massivecore/util/Txt.java
> +			}
This is a micro-duplicate-code instance. Note how these rows are almost the same:
`arguments.set(pageParamIndex, number);`
`arguments.set(arguments.indexOf(oldNumber), number);`

2018-04-02 14:42 UTC, oloflarsson commented on src/com/massivecraft/massivecore/util/Txt.java
> +				arguments.set(pageParamIndex, number);
What if multiple arguments are optional and the page one is among the last ones? Could this yield `ArrayOutOfBoundsException`?

2018-04-03 02:00 UTC, CS-Birb commented on src/com/massivecraft/massivecore/util/Txt.java
> +				arguments.set(pageParamIndex, number);
This was written under the impression that through MassiveCommand's `ApplySwapping`, the args reaching this point would be ordered corresponding to the Parameters, with null values for Unfilled arguments (optional or otherwise).
So assuming everything has gone right up until this point, pageParamIndex should always be within the bounds of the list.

To be safe, I'll add a check in next revision of the PR.

2018-04-03 02:11 UTC, CS-Birb commented on src/com/massivecraft/massivecore/util/Txt.java
> +			}
Implemented in revised commit.

2018-04-03 02:12 UTC, CS-Birb commented
Revised per review

2018-04-15 06:12 UTC, oloflarsson commented on src/com/massivecraft/massivecore/command/MassiveCommand.java
> +		return pageParamIndex;
Should this be `-1`?

2018-04-15 06:12 UTC, oloflarsson commented on src/com/massivecraft/massivecore/util/Txt.java
> +			if (pageParamIndex == -1) pageParamIndex = arguments.indexOf(oldNumber);
Have you taken mix-n-matching into account? @magnusulf coded a system where the argument order can be thrown around. He can probably tell you more about it. Does that logic need to be taken into account in this case?

2018-04-15 06:12 UTC, oloflarsson commented on src/com/massivecraft/massivecore/util/Txt.java
> +			if (pageParamIndex == -1) pageParamIndex = arguments.indexOf(oldNumber);
Some code review from @magnusulf on this ticket would be really helpful!

2018-08-01 07:49 UTC, closed without merging